# For usage instructions see /config/sara/README.md
'USA':
  symptoms:
    'Chills':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Muscle or Body Aches':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Joint Pain':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Headache':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Nausea or Vomiting':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Diarrhea':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Fatigue':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Rash':
      value: true
      type: 'BoolSymptom'
      required: true
      notes: 'Not including the area immediately around the injection site'
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Issues at Injection Site':
      value: true
      type: 'BoolSymptom'
      required: true
      notes: 'Such as pain, redness, swelling or itching'
      threshold_operator: 'Equal'
      group: 1
      severity: 2
    'Miss Work Due to Illness':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 1
    'Unable to do Normal Daily Activities':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 1
    'Receive Care from a Doctor or other Healthcare Professional':
      value: true
      type: 'BoolSymptom'
      required: true
      threshold_operator: 'Equal'
      group: 1
      severity: 1
  # Jurisdictions follow a hierarchy, the hierarchy is defined by nesting jurisdictions
  # in the children: field
  children:
    'State 1':
      children:
        'County 1':
        'County 2':
    'State 2':
      children:
        'County 3':
        'County 4':
